const DAYS = [
{day:1,theme:"Summer's End",eyebrow:"Fact",items:[["Факт","Тёмная половина года","Halloween вырос из кельтского Samhain: конец урожая и начало тёмной половины года."],["Фраза","Say this","The dark half of the year begins."],["Задание","Линия света","Нарисуй линию: день / ночь. Подпиши summer's end. Пришли фото на урок."]]},
{day:2,theme:"Eight October Words",eyebrow:"Make",items:[["Факт","Слова — улики","Детективу сначала нужны точные слова, не страшные истории."],["Задание","Собери венок","Выпиши 8 слов: night, moon, mask, door, light, leaf, wind, home. Составь 2 предложения."],["Голос","15 секунд","Прочитай одно предложение учителю."]]},
{day:3,theme:"Pumpkin Party",eyebrow:"Watch",items:[["Мультик","Смотри 5–7 минут","Найди короткий эпизод Peppa Pig: Pumpkin Party. Не сборник на час."],["Фраза","После просмотра","They make a ______."],["Задание","Одно слово в дело","Допиши пропуск и принеси фразу на урок."]]},
{day:4,theme:"All Hallows' Eve",eyebrow:"Fact",items:[["Факт","Откуда имя","Halloween — это сжатое All Hallows' Eve: канун Дня всех святых, 1 ноября."],["Фраза","Say this","Eve means the night before."],["Задание","Канун","Напиши 2 своих кануна: The night before school / The night before a trip."]]},
{day:5,theme:"The Porch Map",eyebrow:"Make",items:[["Факт","Место дела","Большинство хэллоуинских историй начинается у двери, не в замке."],["Задание","Карта крыльца","Нарисуй свою дверь. Подпиши 5 слов: door, step, window, light, mat."],["Фраза","Say this","The porch is quiet tonight."]]},
{day:6,theme:"Night Sounds",eyebrow:"Voice",items:[["Задание","Голосовое 15 секунд","Запиши 3 ночных звука по-английски: wind / step / knock."],["Фраза","Say this","I can hear the wind."],["На урок","Принеси запись","Одно предложение — достаточно."]]},
{day:31,theme:"Close the File",eyebrow:"Final",items:[["Финал","31 октября","Сегодня можно собрать улики месяца."],["Задание","Закрой дело","5 лучших окон — одно слово каждое."],["Голос","The file is closed","The October file is closed. The porch light is on."]]}
];
